
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Consulbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-check>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-check]]
== Check Fields

Contains checks forr all services in consul.



[float]
=== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp of the event, as measured by the Beat. The precision is in milliseconds. The timezone is UTC.



[float]
=== check.CheckID

required: True

[float]
=== check.Name

required: True

[float]
=== check.Node

required: True

[float]
=== check.Notes

required: True

[float]
=== check.Output

required: True

[float]
=== check.ServiceID

required: True

[float]
=== check.ServiceName

required: True

[float]
=== check.Status

required: True


[float]
=== node.Address

required: True

[float]
=== node.Node

required: True


[float]
=== node.TaggedAddresses.Lan

required: True

[float]
=== node.TaggedAddresses.Wan

required: True


[float]
=== service.Address

required: True

[float]
=== service.ID

required: True

[float]
=== service.Port

format: dotted notation.

required: True

[float]
=== service.Service

required: True

[float]
=== service.Tags

required: True

